name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Accountability Unit Tests
    runs-on:
      - self-hosted
      - windows
      - x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Standard checkout step :contentReference[oaicite:2]{index=2}

      - name: Start SQL Server engine (CI-only)
        run: docker run -d --name sqlci -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=${{ secrets.SA_PASSWORD }}" -p 1433:1433 mcr.microsoft.com/mssql/server:2022-latest
        # Single-line invocation avoids any shell-specific line-continuation issues :contentReference[oaicite:3]{index=3}

      - name: Wait for SQL Server to initialize
        run: Start-Sleep -Seconds 30  # Allows SQL Server to fully start :contentReference[oaicite:4]{index=4}

      - name: Build application Docker image
        run: docker build -t accountability-ci-pipeline .
        # Builds the test image from your Dockerfile :contentReference[oaicite:5]{index=5}

      - name: Run pytest integration tests
        run: docker run --rm --network=host -e DB_SERVER=localhost -e DB_NAME=master -e DB_USERNAME=sa -e DB_PASSWORD="${{ secrets.SA_PASSWORD }}" accountability-ci-pipeline
        # Single-line ensures Docker parses all flags and image name correctly :contentReference[oaicite:6]{index=6}

      - name: Tear down SQL Server
        if: always()
        run: docker rm -f sqlci
        # Cleans up the SQL Server container even if tests fail :contentReference[oaicite:7]{index=7}

# name: CI Pipeline

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     name: accountability unit tests
#     #runs-on: ubuntu-latest
#     runs-on:
#     - self-hosted
#     - windows
#     - x64
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build Docker image
#         run: |
#           docker build -t myapp -f ./Dockerfile .

#       - name: Run tests with pytest inside Docker container
#         run: |
#           docker run --rm myapp pytest


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged == true

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Azure CLI
  #       uses: azure/setup-azurecli@v1
  #       with:
  #         version: '2.28.0'

  #     - name: Install Azure DevOps CLI extension
  #       run: |
  #         az extension add --name azure-devops

  #     - name: Deploy to Azure DevOps
  #       uses: azure/cli-action@v2
  #       with:
  #         azcliversion: '2.28.0'
  #       env:
  #         AZURE_DEVOPS_EXT_PATVAR: ${{ secrets.AZURE_DEVOPS_PAT }}
  #       run: |
  #         az devops login --token $AZURE_DEVOPS_EXT_PATVAR
  #         git remote add azure https://dev.azure.com/your_organization/your_project/_git/your_repo
  #         git push azure main